### ISSUE TITLE
Plugin not loaded at startup with error message

### ISSUE THREAD

**Issue by bschtl** [oddbear/Loupedeck.VolumeControl.Plugin#1]
Sometimes the plugin is not loaded at the startup of loupedeck live s, the loupedeck software then produces an error message, see screenshot. 
![Screenshot 2022-12-07 141112](https://user-images.githubusercontent.com/99877719/208159715-f655edb9-365e-43fc-be7e-9a7ac38be2c3.png)

If I can do anything to help solve this issue, I am glad to help.
Thank you for the plugin!

**Comment by oddbear** [comment]
Oh sorry, did not see this one before now. 😔 But thanks for reporting.
This is interesting. It's hard to tell what it can be. Could you provide some more information about your setup.
Is it Windows 10 or 11. What version of the Louepdeck software are you using etc.

**Comment by bschtl** [comment]
Sorry for the late reply.
Since updating to latest version of Loupedeck Configuration, this error message doesn't show up anymore. So I think you can close the issue. If it reappers I will create a new issue with more details about my system, etc.
