### ISSUE TITLE
Loupedeck 6 software update

### ISSUE THREAD

**Issue by balzerinyourface** [oddbear/Loupedeck.VolumeControl.Plugin#8]
With the new update of loupedeck the software immediately crashes. Wondering if there is any planned updates to the volume control plugin.

Thanks

**Comment by oddbear** [comment]
Hi, I got access to the beta version, and an update should already have been submitted.
I will check on the progress later (on phone now), and if it’s not approved, I can make a release here for manual install.

**Comment by balzerinyourface** [comment]
Good to know. Thank you. This plugin is a life saver 🙌

**Comment by oddbear** [comment]
Adding the manual install file here, I think this was the one I submitted.
It's not in the store yet, so not sure when it will be out through there.
[VolumeControlPlugin.zip](https://github.com/user-attachments/files/17244417/VolumeControlPlugin.zip)

**Comment by balzerinyourface** [comment]
Amazing!  Works like a charm.  Thank you.

**Comment by bento-ux-ui** [comment]
Hi, wondering how to manually install plugin ? Loupedeck documentation says "Verify that "LoupedeckPluginPackageInstaller" is opening the file" . Can't find that program anywhere. Had a hard time to find where loupedeck was even installed... Into Logi plugins? Very odd. Any clue on how to install, any help would be very much appreciated.  Thx
Edit : Btw @oddbear thanks a lot for your plugin it's what i use loupedeck for 99% of the time.
Edit 2 : Found that you can install from loupedeck software... feel dumb, yet not mentioned anywhere in their documentation...
